export const eventTypeColors = {
  "Hours": "#448",
  "Education": "#484",
  "Arts": "#884",
  "Performance": "#844",
  "Costuming": "#488",
  "Event": "#22a",
  "Gaming": "#646",
  "Music": "#848",
  "Species": "#a79",
  "Social": "#152",
  "Writing": "#860",
  "Unknown": "#62a"
}

export const eventTypeOrdering = [
  "Hours",
  "Event",
  "Gaming",
  "Performance",
  "Music",
  "Species",
  "Arts",
  "Costuming",
  "Education",
  "Social",
  "Writing",
  "Unknown"
]

export const shortLocationNames = {
  "SJCC: Con Ops / Zookeepers": "Con Ops / Zookeepers",
  "SJCC: Dealers Den (LL20BCD/LL21BCDEF)": "SJCC: Lower Level",
  "SJCC: Registration (The Hub)": "SJCC: The Hub",
  "Hilton: Art Show (Almaden Ballroom)": "Hilton: Almaden Ballroom",
  "Marriott: Fursuit Lounge (San Carlos)": "Marriott: San Carlos",
  "Marriott: Marriott Stage (Salon I to VI)": "Marriott Stage",
  "Hilton: Escape Room (Winchester 1)": "Hilton: Winchester 1",
  "Hilton: Gaming (Market)": "Hilton: Market",
  "SJCC: Rehearsal Area (220B)": "SJCC: 220B",
  "SJCC: Main Stage (220A)": "Main Stage (SJCC 220A)",
  "SJCC: SJCC Courtyard": "SJCC: Courtyard",
  "SJCC: Recharge Room (114)": "SJCC: 114",
  "SJCC: Third Stage (211CD)": "SJCC: 211CD",
  "SJCC: 220C (Fursuit Lounge)": "SJCC: 220C",
  "Hilton: Escape Room (Winchester I)": "Hilton: Winchester I",
  "SJCC: 211B (Photoshoot)": "SJCC: 211B",
  "SJCC: Zookeepers (SR4)": "SJCC: SR4",
  "SJCC: AD Dealer's Den (212)": "SJCC: 212",
  "SJCC: 113 (Pop-Up Fursuit Lounge)": "SJCC: 113",
  "SJCC: 220B'C' (Arcade)": "SJCC: 220B'C'"
}

export const cohesiveLocationOrder = [
  "SJCC: Main Stage (220A)",
  "Marriott: Marriott Stage (Salon I to VI)",
  "Hilton: Plaza",
  "Hilton: San Carlos",
  "Hilton: San Pedro",
  "Hilton: Santa Clara",
  "Hilton: University",
  "Marriott: Almaden",
  "Marriott: Blossom Hill",
  "Marriott: Guadalupe",
  "Marriott: Willow Glen III",
  "Marriott: Clara's Room (Willow Glenn III)",
  "SJCC: Rehearsal Area (220B)",
  "SJCC: 211A",
  "SJCC: Third Stage (211CD)",
  "SJCC: Parade Plans",
  "Tech: Exhibit Hall",
  "Hilton: Gaming (Market)",
  "SJCC: 220B'C' (Arcade)",
  "SJCC: Registration (The Hub)",
  "SJCC: Dealers Den (LL20BCD/LL21BCDEF)",
  "SJCC: AD Dealer's Den (212)",
  "Hilton: Art Show (Almaden Ballroom)",
  "Marriott: Willow Glen I-II",
  "Hilton: Escape Room (Winchester I)",
  "SJCC: 220C (Fursuit Lounge)",
  "Marriott: Fursuit Lounge (San Carlos)",
  "SJCC: 113 (Pop-Up Fursuit Lounge)",
  "SJCC: 211B (Photoshoot)",
  "Hilton: Santa Clara Foyer",
  "SJCC: Recharge Room (114)",
  "Hilton: Executive Boardroom",
  "Marriott: 3B Conference Room",
  "SJCC: Con Ops",
  "SJCC: Zookeepers (SR4)",
]